project_path: .
ddconfig_path: configs/ddconfigs/whale-sequences.json
model_path: models/sequifier-default-best-1500.onnx
data_path: data/whale-sequences-split2.csv
read_format: csv

selected_columns: ["Coda", "Ornamentation", "Duration", "VocalizationChange", "SpeakerChange"] # should include all target column, can include additional columns
target_columns: ["Coda", "Ornamentation", "Duration", "VocalizationChange", "SpeakerChange"] # should include all target column, can include additional columns
target_column_types: # 'criterion' in training_spec must also be adapted
  Coda: categorical
  Ornamentation: categorical
  Duration: real
  VocalizationChange: categorical
  SpeakerChange: categorical

output_probabilities: false
map_to_id: true
device: cuda
seq_length: 25
inference_batch_size: 1

autoregression: true
autoregression_additional_steps: 20