project_path: .
ddconfig_path: configs/ddconfigs/whale-dialogues.json
model_path: models/sequifier-dialogue4-best-5000.onnx
data_path: data/whale-dialogues-split2.csv
read_format: csv

selected_columns: ["Coda1", "Ornamentation1", "Duration1", "Coda2", "Ornamentation2", "Duration2"] # should include all target column, can include additional columns
target_columns: ["Coda1", "Ornamentation1", "Duration1", "Coda2", "Ornamentation2", "Duration2"] # should include all target column, can include additional columns
target_column_types: # 'criterion' in training_spec must also be adapted
  Coda1: categorical
  Ornamentation1: categorical
  Duration1: real
  Coda2: categorical
  Ornamentation2: categorical
  Duration2: real

output_probabilities: false
map_to_id: true
device: mps
seq_length: 25
inference_batch_size: 1

autoregression: true
autoregression_additional_steps: 20
sample_from_distribution_columns: