project_path: .
model_name: default
read_format: csv
ddconfig_path: configs/ddconfigs/whale-sequences.json

selected_columns: ["Coda", "Ornamentation", "Duration", "VocalizationChange", "SpeakerChange"] # should include all target column, can include additional columns
target_columns: ["Coda", "Ornamentation", "Duration", "VocalizationChange", "SpeakerChange"] # should include all target column, can include additional columns
target_column_types: # 'criterion' in training_spec must also be adapted
  Coda: categorical
  Ornamentation: categorical
  Duration: real
  VocalizationChange: categorical
  SpeakerChange: categorical

seq_length: 25
inference_batch_size: 1

export_onnx: true

model_spec:
  d_model: 256
  nhead: 8
  d_hid: 256
  nlayers: 3
training_spec:
  device: cuda
  epochs: 1000
  iter_save: 50
  batch_size: 100
  log_interval: 3
  lr: 0.00001
  accumulation_steps: 1
  dropout: 0.2
  criterion:
    Coda: CrossEntropyLoss
    Ornamentation: CrossEntropyLoss
    Duration: MSELoss
    VocalizationChange: CrossEntropyLoss
    SpeakerChange: CrossEntropyLoss
  optimizer:
    name: AdamW
  scheduler:
    name: CosineAnnealingLR
    T_max: 100
    eta_min: 0.000001
  continue_training: true